# Generated by Django 2.2.16 on 2023-02-24 10:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0009_auto_20230224_1310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={
                'verbose_name': 'группа',
                'verbose_name_plural': 'группы',
            },
        ),
    ]
