# Generated by Django 2.2.16 on 2023-02-24 10:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0010_auto_20230224_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'комментарии',
            },
        ),
        migrations.AlterModelOptions(
            name='follow',
            options={
                'verbose_name': 'подписка',
                'verbose_name_plural': 'подписки',
            },
        ),
    ]
